config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cocktails#home"

  resources :cocktails, only: [ :show, :index, :new, :create ] do
    resources :doses, only: [ :create ]
    resources :reviews, only: [ :create ]
  end

  resources :doses, only: :destroy
  resources :cocktails, only: :destroy
  resources :reviews, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  scope :next, lambda {|id| where("id > ?",id).order("id ASC") } # this is the default ordering for AR
  scope :previous, lambda {|id| where("id < ?",id).order("id DESC") }

  def next
    Cocktail.next(self.id).first
  end

  def previous
    Cocktail.previous(self.id).first
  end
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates :description, presence: :true
  validates :cocktail, presence: :true, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail

  validates :content, presence: true
  validates :commenter, presence: true
  validates :rating, presence: true
  validates :rating, numericality: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :warning, :danger, :info
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :destroy]



  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
    @review = Review.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail, success: "Cocktail created !"
    else
      render :new
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :image_url)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "cocktails/show"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new(review_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail, anchor: "anchor-review")
    else
      render "cocktails/show"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @cocktail = @review.cocktail
    @review.destroy
    redirect_to cocktail_path(@cocktail, anchor: "anchor-review")
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating, :cocktail_id, :commenter)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/home.html.erb
<div class="banner-home" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 0%, rgba(0,0,0,0.3) 50%), url('http://cdn.skim.gs/images/sangria-cocktail_e9s3m1/3-spiced-rum-cocktails'); height: 100vh; background-position: center;">
    <h1>HELLO.</h1>
    <h2><span id="title-typed-text"></span></h2>
    <div class="btn-yellow">
    <%= link_to "Discover", cocktails_path %>
    </div>

</div>

app/views/cocktails/index.html.erb
<%= render "layouts/navbar" %>
<div class="container">
  <h1 class="text-center">Our cocktails</h1>
  <h4 class="text-center">The most loved recipes gathered in one place.</h4>
  <div class="cards">
    <% @cocktails.each do |c| %>
      <div class="card" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 0%, rgba(0,0,0,0.3) 50%), url('<%= c.image_url %>'); background-position: center;">
        <h2><%= c.name %></h2>
        <%= link_to c.name, cocktail_path(c.id), class: "card-link" %>
    </div>
  <% end %>
  </div>
  <%= link_to "Add a cocktail", new_cocktail_path, class: "btn-yellow" %>
</div>

<%= render "layouts/footer" %>

app/views/cocktails/new.html.erb
<%= render "layouts/navbar" %>
<div class="container">
  <div class="create-recipe">
    <div class="create-form">
  <h1>CREATE A NEW COCKTAIL</h1>

  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :image_url, placeholder: "https://kitt.lewagon.com/placeholder/cities/shanghai" %>

    <%= f.submit "Create a cocktail", class: "submit", id: "sweet-alert-demo" %>
  <% end %>
</div>
</div>
</div>
<%= render "layouts/footer" %>

app/views/cocktails/show.html.erb
<%= render "layouts/navbar" %>

<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 0%, rgba(0,0,0,0.3) 50%), url('<%= @cocktail.image_url %>'); height: 50vh; background-position: center;">
  <div class="banner-header">
    <h1><%= @cocktail.name %></h1>
  </div>
  <div class="banner-content" id="sweet-alert-delete">
  <%= link_to image_tag('rubbish.png'), cocktail_path(@cocktail.id), method: :delete %>
  </div>
</div>

<div class="content" >
  <div class="row">

  <div class="col-xs-12 col-sm-6">
    <h3 class="green-title"><strong><%= @cocktail.name %>'s recipe :</strong></h3>
    <ul class="list-unstyled">
      <% @cocktail.doses.each do |d| %>
        <li class="dose"><strong><%= d.description %></strong> <%= d.ingredient.name %> <%= link_to image_tag('x_close.png'), dose_path(d), method: :delete %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="col-xs-12 col-sm-6">
      <div class="form-ingredient">
        <h4>Add ingredient :</h4>
        <%= simple_form_for [ @cocktail, @dose ] do |f| %>
          <%= f.association :ingredient, prompt: "Choose an ingredient" %>
          <%= f.input :description, label: "Quantity" %>
          <%= f.submit "Add", class: "submit" %>
        <% end %>
      </div>
    </div>
  </div>



  <div class="review">
    <h2 class="text-center"><strong>Comments</strong> (<%= @cocktail.reviews.count %>)</h2>
    <a name="anchor-review"></a>
    <div class="posted-message">
      <% if @cocktail.reviews.any? %>
        <% @cocktail.reviews.each do |r| %>
          <div class="delete-review">
            <%= link_to image_tag('x_close.png'), review_path(r), method: :delete %>
          </div>
          <div class="message-box">
            <div class="avatar-large">
              <%= image_tag "cocktail-reviews.png", id: "review-picture" %>
            </div>
            <div class="message-name">
              <h4><%= r.commenter %></h4>
              <p><%= Date.new.to_time.strftime('%B %e') %></p>
              <p><%= Date.new.to_time.strftime('at %l:%M %p') %></p>
            </div>
            <div class="message-body">
              <p><%= r.content %></p>
            </div>
            <div class="message-rating">
              <p class="rating-title">Rating</p>
              <p class="rating"><%= r.rating %>/5</p>
            </div>
        </div>
        <% end %>
        <p class="green-title average-rating"><%= @cocktail.name %> has an average rating of <%= @cocktail.reviews.average("rating") %>/5</p>
      <% else %>
        <p class="no-comments">There are no comments yet.</p>
      <% end %>
    </div>

    <div class="posted-message">
      <div class="form-review">
        <h3>Add a review :</h3>
        <%= simple_form_for [ @cocktail, @review ] do |f| %>
          <%= f.input :commenter, label: "Your name"%>
          <%= f.input :rating %>
          <%= f.input :content, label: "Your review" %>
          <%= f.submit "Add a review", class: "submit" %>
        <% end %>
    </div>
    </div>
  </div>
  <div class="downpage-links">
    <% if @cocktail.previous.presence %>
      <p><%= link_to "Previous cocktail", @cocktail.previous %></p>
    <% end %>
      <p><%= link_to "Go back to list", cocktails_path %></p>
    <% if @cocktail.next.presence %>
      <p><%= link_to "Next cocktail", @cocktail.next %></p>
    <% end %>
  </div>

</div>

<%= render "layouts/footer" %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Our cocktails are ade with <i class="fa fa-heart"></i> at Le Wagon.
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "cocktail.png", id: "logo" %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <a href="/cocktails" class="navbar-wagon-item navbar-wagon-link">Our cocktails</a>
    <a href="/cocktails/new" class="navbar-wagon-item navbar-wagon-link">Add your recipe</a>
    <a href="#" class="navbar-wagon-item navbar-wagon-link">About</a>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <a href="#">
          <%= image_tag "photo.png", id: "profile" %>
        </a>

        <!-- <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul> -->
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
 <!--  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div> -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>